[package]
name = "mop"
version = "0.2.1"
edition = "2021"
description = "Clear command-line clutter"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["cargo", "derive"] }
crossterm = "0.28.1"
